package com.cressy.schoolmanagementsystem.enums;

public enum Roles {
    ADMIN,
    MATHS_TEACHER,
    ENGLISH_TEACHER,
    PHYSICS_TEACHER,
    CHEMISTRY_TEACHER,
    HISTORY_TEACHER,
    GOVERNMENT_TEACHER,
    BIOLOGY_TEACHER,
    ART_TEACHER,
    NONE,
    GEOGRAPHY_TEACHER,
    SOCIAL_STUDY_TEACHER,
    CIVIC_EDUCATION_TEACHER,
    BASIC_SCIENCE_TEACHER,
    HEAD_BOY,
    HEAD_GIRL,
    SOCIAL_PREFECT,
    UTILITY_PREFECT,
    LABOUR_PREFECT,
}
